/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HeadingShifter
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/types/type.ts
var HEADINGS = [0, 1, 2, 3, 4, 5, 6];

// src/settings.ts
var DEFAULT_SETTINGS = {
  limitHeadingFrom: 1,
  overrideTab: false,
  styleToRemove: { ul: true, ol: true }
};
var HeadingShifterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Lower limit of Heading").setDesc("The lower Heading Size that will be decreased by the Heading Shift ").addDropdown((dropdown) => {
      const headingOptions = HEADINGS.reduce((prev, heading) => {
        return __spreadProps(__spreadValues({}, prev), { [heading]: String(heading) });
      }, {});
      dropdown.addOptions(headingOptions).setValue(String(this.plugin.settings.limitHeadingFrom)).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.limitHeadingFrom = Number(value);
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian.Setting(containerEl).setName("Enable override tab behavior").setDesc('Tab execute "Increase Headings" and Shift-Tab execute "Decrease Headings"').addToggle((toggle) => toggle.setValue(this.plugin.settings.overrideTab).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.overrideTab = value;
      yield this.plugin.saveSettings();
    })));
    containerEl.createEl("h3", { text: "Style to remove" });
    containerEl.createEl("p", { text: "If this style is at the beginning of a line, replace it by a Heading:" });
    new import_obsidian.Setting(containerEl).setName("Unordered list").setDesc("-").addToggle((toggle) => toggle.setValue(this.plugin.settings.styleToRemove.ul).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.styleToRemove.ul = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian.Setting(containerEl).setName("Ordered list").setDesc("1., 2. ,3. ,...").addToggle((toggle) => toggle.setValue(this.plugin.settings.styleToRemove.ol).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.styleToRemove.ol = value;
      yield this.plugin.saveSettings();
    })));
  }
};

// src/services/obsidianService.ts
var import_obsidian2 = require("obsidian");
var ObsidianService = class {
  constructor() {
  }
  getEditorFromState(state) {
    return state.field(import_obsidian2.editorViewField).editor;
  }
  createKeymapRunCallback(config) {
    const check = config.check || (() => true);
    const { run } = config;
    return (view) => {
      const editor = this.getEditorFromState(view.state);
      if (!check(editor)) {
        return false;
      }
      const shouldStopPropagation = run(editor);
      return shouldStopPropagation;
    };
  }
};

// src/services/interfaceService.ts
var import_obsidian3 = require("obsidian");

// src/ui/icon.ts
var icon_increase_heading = `
<path d="M100 50L81.25 68.1865L81.25 31.8135L100 50Z" fill="currentColor" />
<line x1="5" y1="37" x2="73" y2="37"  stroke="currentColor" stroke-width="10" stroke-linecap="round" />
<line x1="52" y1="8" x2="52" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round" />
<line x1="5" y1="62" x2="73" y2="62"  stroke="currentColor" stroke-width="10" stroke-linecap="round" />
<line x1="27" y1="8" x2="27" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round" />`;
var icon_decrease_heading = `<path d="M2.50422e-07 50L18.75 31.8135L18.75 68.1865L2.50422e-07 50Z" fill="currentColor" />
<line x1="27" y1="37" x2="95" y2="37"  stroke="currentColor" stroke-width="10" stroke-linecap="round" />
<line x1="74" y1="8" x2="74" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round" />
<line x1="27" y1="62" x2="95" y2="62"  stroke="currentColor" stroke-width="10" stroke-linecap="round" />
<line x1="49" y1="8" x2="49" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round" />
`;
var icon_heading_0 = `
<path d="M12 22H88"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<line x1="71" y1="8" x2="71" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M48.9929 65.7955C46.3509 65.786 44.0687 65.1752 42.1463 63.9631C40.224 62.7509 38.742 61.0038 37.7003 58.7216C36.6586 56.4394 36.1425 53.7027 36.152 50.5114C36.1615 47.3106 36.6823 44.5928 37.7145 42.358C38.7562 40.1231 40.2334 38.4233 42.1463 37.2585C44.0687 36.0937 46.3509 35.5114 48.9929 35.5114C51.6349 35.5114 53.9171 36.0985 55.8395 37.2727C57.7618 38.4375 59.2438 40.1373 60.2855 42.3722C61.3272 44.607 61.8433 47.3201 61.8338 50.5114C61.8338 53.7216 61.313 56.4678 60.2713 58.75C59.2296 61.0322 57.7476 62.7794 55.8253 63.9915C53.9124 65.1941 51.6349 65.7955 48.9929 65.7955ZM48.9929 59.375C50.3565 59.375 51.474 58.6648 52.3452 57.2443C53.2259 55.8144 53.6615 53.5701 53.652 50.5114C53.652 48.5133 53.4531 46.8797 53.0554 45.6108C52.6577 44.3419 52.1084 43.4044 51.4077 42.7983C50.7069 42.1828 49.902 41.875 48.9929 41.875C47.6293 41.875 46.5166 42.5663 45.6548 43.9489C44.7931 45.3314 44.3527 47.5189 44.3338 50.5114C44.3243 52.5473 44.5185 54.2235 44.9162 55.5398C45.3139 56.8466 45.8632 57.8125 46.5639 58.4375C47.2741 59.0625 48.0838 59.375 48.9929 59.375Z"  fill="currentColor"/>
<line x1="11" y1="78" x2="89" y2="78"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M28 8L28 92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>`;
var icon_heading_1 = `
<path d="M12 22H88"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<line x1="71" y1="8" x2="71" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M55.576 35.9091V65H47.6783V43.1818H47.5078L41.1442 46.9886V40.2841L48.3033 35.9091H55.576Z"  fill="currentColor"/>
<line x1="11" y1="78" x2="89" y2="78"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M28 8L28 92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>`;
var icon_heading_2 = `
<path d="M12 22H88"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<line x1="71" y1="8" x2="71" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M38.0021 65V59.3182L48.8544 50.3409C49.5741 49.7443 50.1896 49.1856 50.701 48.6648C51.2218 48.1345 51.6196 47.59 51.8942 47.0312C52.1783 46.4725 52.3203 45.8523 52.3203 45.1705C52.3203 44.4223 52.1593 43.7831 51.8374 43.2528C51.5249 42.7225 51.0893 42.3153 50.5305 42.0312C49.9718 41.7377 49.3279 41.5909 48.5987 41.5909C47.8696 41.5909 47.2256 41.7377 46.6669 42.0312C46.1177 42.3248 45.6915 42.7557 45.3885 43.3239C45.0855 43.892 44.9339 44.5833 44.9339 45.3977H37.4339C37.4339 43.3523 37.8932 41.5909 38.8118 40.1136C39.7304 38.6364 41.0277 37.5 42.7038 36.7045C44.38 35.9091 46.3449 35.5114 48.5987 35.5114C50.9283 35.5114 52.9453 35.8854 54.6499 36.6335C56.3639 37.3722 57.6849 38.4138 58.6129 39.7585C59.5504 41.1032 60.0192 42.6799 60.0192 44.4886C60.0192 45.6061 59.7872 46.7187 59.3232 47.8267C58.8591 48.9252 58.0258 50.142 56.8232 51.4773C55.6205 52.8125 53.9112 54.4034 51.6953 56.25L48.968 58.5227V58.6932H60.3317V65H38.0021Z"  fill="currentColor"/>
<line x1="11" y1="78" x2="89" y2="78"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M28 8L28 92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>`;
var icon_heading_3 = `
<path d="M12 22H88"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<line x1="71" y1="8" x2="71" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M49.2994 65.3977C47.0077 65.3977 44.9717 65.0047 43.1914 64.2188C41.4206 63.4233 40.0285 62.3295 39.0153 60.9375C38.002 59.5455 37.4906 57.9451 37.4812 56.1364H45.4357C45.4452 56.6951 45.6156 57.197 45.9471 57.642C46.288 58.0777 46.752 58.4186 47.3391 58.6648C47.9263 58.911 48.5986 59.0341 49.3562 59.0341C50.0853 59.0341 50.7293 58.9062 51.288 58.6506C51.8467 58.3854 52.2823 58.0208 52.5948 57.5568C52.9073 57.0928 53.0588 56.5625 53.0494 55.9659C53.0588 55.3788 52.8789 54.858 52.5096 54.4034C52.1497 53.9489 51.6431 53.5937 50.9897 53.3381C50.3363 53.0824 49.5835 52.9545 48.7312 52.9545H45.7766V47.5H48.7312C49.5172 47.5 50.2085 47.3722 50.805 47.1165C51.4111 46.8608 51.8799 46.5057 52.2113 46.0511C52.5522 45.5966 52.7179 45.0758 52.7085 44.4886C52.7179 43.9205 52.5806 43.4186 52.2965 42.983C52.0124 42.5473 51.6147 42.2064 51.1033 41.9602C50.6014 41.714 50.0191 41.5909 49.3562 41.5909C48.6365 41.5909 47.9925 41.7187 47.4244 41.9744C46.8656 42.2301 46.4253 42.5852 46.1033 43.0398C45.7814 43.4943 45.6156 44.0152 45.6062 44.6023H38.0494C38.0588 42.822 38.5465 41.25 39.5124 39.8864C40.4878 38.5227 41.823 37.4527 43.5181 36.6761C45.2132 35.8996 47.1592 35.5114 49.3562 35.5114C51.5058 35.5114 53.4045 35.8759 55.0522 36.6051C56.7094 37.3343 58.002 38.3381 58.93 39.6165C59.8675 40.8854 60.3316 42.339 60.3221 43.9773C60.341 45.6061 59.7823 46.9413 58.646 47.983C57.5191 49.0246 56.0891 49.6402 54.3562 49.8295V50.0568C56.7047 50.3125 58.4708 51.0322 59.6545 52.2159C60.8382 53.3902 61.4206 54.8674 61.4016 56.6477C61.4111 58.3523 60.8997 59.8627 59.8675 61.179C58.8448 62.4953 57.4196 63.5275 55.592 64.2756C53.7738 65.0237 51.6763 65.3977 49.2994 65.3977Z"  fill="currentColor"/>
<line x1="11" y1="78" x2="89" y2="78"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M28 8L28 92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>`;
var icon_heading_4 = `
<path d="M12 22H88"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<line x1="71" y1="8" x2="71" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M37.1048 60.4545V54.3182L48.8093 35.9091H54.3775V44.0909H51.1957L44.8888 54.0909V54.3182H62.1616V60.4545H37.1048ZM51.2525 65V58.5795L51.4229 55.9091V35.9091H58.8093V65H51.2525Z"  fill="currentColor"/>
<line x1="11" y1="78" x2="89" y2="78"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M28 8L28 92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>`;
var icon_heading_5 = `
<path d="M12 22H88"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<line x1="71" y1="8" x2="71" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M49.7006 65.3977C47.4658 65.3977 45.4819 65.0047 43.7489 64.2188C42.0254 63.4233 40.6665 62.3295 39.6722 60.9375C38.6874 59.5455 38.1855 57.9451 38.1665 56.1364H45.837C45.8654 57.1402 46.2537 57.9403 47.0018 58.5369C47.7594 59.1335 48.659 59.4318 49.7006 59.4318C50.5056 59.4318 51.2158 59.2614 51.8313 58.9205C52.4469 58.5701 52.9298 58.0777 53.2802 57.4432C53.6306 56.8087 53.801 56.0701 53.7915 55.2273C53.801 54.375 53.6306 53.6364 53.2802 53.0114C52.9298 52.3769 52.4469 51.8892 51.8313 51.5483C51.2158 51.1979 50.5056 51.0227 49.7006 51.0227C48.8673 51.0227 48.0955 51.2263 47.3853 51.6335C46.6845 52.0312 46.1684 52.5852 45.837 53.2955L38.9052 51.9318L40.0415 35.9091H59.587V42.2159H46.5188L45.9506 48.6364H46.1211C46.5756 47.7557 47.3616 47.0265 48.479 46.4489C49.5965 45.8617 50.8938 45.5682 52.3711 45.5682C54.104 45.5682 55.6476 45.9706 57.0018 46.7756C58.3654 47.5805 59.4402 48.6932 60.2262 50.1136C61.0217 51.5246 61.4147 53.1534 61.4052 55C61.4147 57.0265 60.9317 58.8258 59.9563 60.3977C58.9904 61.9602 57.6315 63.1866 55.8796 64.0767C54.1277 64.9574 52.0681 65.3977 49.7006 65.3977Z"  fill="currentColor"/>
<line x1="11" y1="78" x2="89" y2="78"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M28 8L28 92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>`;
var icon_heading_6 = `
<path d="M12 22H88"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<line x1="71" y1="8" x2="71" y2="92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M49.3995 65.3977C47.7044 65.3977 46.0946 65.1326 44.57 64.6023C43.0548 64.0625 41.7101 63.215 40.5359 62.0597C39.3616 60.9044 38.4383 59.3987 37.766 57.5426C37.1031 55.6866 36.7764 53.4375 36.7859 50.7955C36.7953 48.4375 37.0984 46.3163 37.695 44.4318C38.301 42.5473 39.158 40.9422 40.266 39.6165C41.3834 38.2907 42.7186 37.2775 44.2717 36.5767C45.8247 35.8665 47.5529 35.5114 49.4563 35.5114C51.5965 35.5114 53.4809 35.9233 55.1097 36.7472C56.7385 37.571 58.0359 38.6742 59.0018 40.0568C59.9772 41.4299 60.5453 42.9451 60.7063 44.6023H52.9222C52.7423 43.7784 52.3256 43.1771 51.6722 42.7983C51.0283 42.41 50.2897 42.2159 49.4563 42.2159C47.7991 42.2159 46.5823 42.9356 45.8058 44.375C45.0387 45.8144 44.6457 47.7083 44.6268 50.0568H44.7972C45.1665 49.1667 45.7253 48.4044 46.4734 47.7699C47.2215 47.1354 48.0927 46.6477 49.087 46.3068C50.0813 45.9659 51.1325 45.7955 52.2404 45.7955C54.0018 45.7955 55.5406 46.1932 56.8569 46.9886C58.1826 47.7841 59.2148 48.8731 59.9535 50.2557C60.6921 51.6383 61.0567 53.2197 61.0472 55C61.0567 57.0833 60.5643 58.9062 59.57 60.4688C58.5851 62.0312 57.2167 63.2434 55.4648 64.1051C53.713 64.9669 51.6912 65.3977 49.3995 65.3977ZM49.3427 59.4318C50.1287 59.4318 50.8247 59.2519 51.4308 58.892C52.0463 58.5322 52.5245 58.0398 52.8654 57.4148C53.2158 56.7898 53.3862 56.0795 53.3768 55.2841C53.3862 54.4792 53.2158 53.7689 52.8654 53.1534C52.5245 52.5284 52.0463 52.036 51.4308 51.6761C50.8247 51.3163 50.1287 51.1364 49.3427 51.1364C48.765 51.1364 48.23 51.2405 47.7376 51.4489C47.2546 51.6477 46.8332 51.9366 46.4734 52.3153C46.1135 52.6847 45.8294 53.125 45.6211 53.6364C45.4222 54.1383 45.3181 54.6875 45.3086 55.2841C45.3181 56.0795 45.498 56.7898 45.8484 57.4148C46.1987 58.0398 46.677 58.5322 47.283 58.892C47.8891 59.2519 48.5756 59.4318 49.3427 59.4318Z"  fill="currentColor"/>
<line x1="11" y1="78" x2="89" y2="78"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>
<path d="M28 8L28 92"  stroke="currentColor" stroke-width="10" stroke-linecap="round"/>`;

// src/services/interfaceService.ts
var InterfaceService = class {
  constructor() {
    __publicField(this, "addIcons", () => {
      (0, import_obsidian3.addIcon)("headingShifter_decreaseIcon", icon_decrease_heading);
      (0, import_obsidian3.addIcon)("headingShifter_increaseIcon", icon_increase_heading);
      (0, import_obsidian3.addIcon)("headingShifter_heading0", icon_heading_0);
      (0, import_obsidian3.addIcon)("headingShifter_heading1", icon_heading_1);
      (0, import_obsidian3.addIcon)("headingShifter_heading2", icon_heading_2);
      (0, import_obsidian3.addIcon)("headingShifter_heading3", icon_heading_3);
      (0, import_obsidian3.addIcon)("headingShifter_heading4", icon_heading_4);
      (0, import_obsidian3.addIcon)("headingShifter_heading5", icon_heading_5);
      (0, import_obsidian3.addIcon)("headingShifter_heading6", icon_heading_6);
    });
  }
  exec() {
    this.addIcons();
  }
};

// src/features/shiftHeading/operation.ts
var import_obsidian4 = require("obsidian");

// src/utils/editorChange.ts
var composeLineChanges = (editor, lineNumbers, changeCallback, settings) => {
  const editorChange = [];
  for (const line of lineNumbers) {
    const shifted = changeCallback(editor.getLine(line), settings);
    editorChange.push({
      text: shifted,
      from: { line, ch: 0 },
      to: {
        line,
        ch: editor.getLine(line).length
      }
    });
  }
  return editorChange;
};

// src/utils/range.ts
var setMin = (prev, cur) => {
  if (prev == void 0 || prev !== void 0 && cur < prev) {
    return cur;
  }
  return prev;
};
var setMax = (prev, cur) => {
  if (prev == void 0 || prev !== void 0 && cur > prev) {
    return cur;
  }
  return prev;
};
var createRange = (start, num) => Array.from(Array(num), (v, k) => k + start);

// src/utils/markdown.ts
var checkHeading = (content) => {
  const match = content.match(/^(#+) /);
  if (!match || !match[1])
    return 0;
  return match[1].length;
};
var checkFence = (content) => {
  const backticks = content.match(/^(`{3,})/);
  if (backticks && backticks[1])
    return { fenceType: "`", fenceNum: backticks[1].length };
  const tildes = content.match(/^(~{3,})/);
  if (tildes && tildes[1])
    return { fenceType: "~", fenceNum: tildes[1].length };
  return null;
};
var getFenceStatus = (prev, current) => {
  if (!current)
    return prev;
  if (!prev)
    return current;
  if (current.fenceType == prev.fenceType && current.fenceNum >= prev.fenceNum) {
    return null;
  }
  return prev;
};
var getHeadingLines = (editor, from, to) => {
  let headingLines = [];
  let minHeading = void 0;
  let maxHeading = void 0;
  let fence = null;
  for (let line = Math.min(from, to); line <= Math.max(from, to); line++) {
    fence = getFenceStatus(fence, checkFence(editor.getLine(line)));
    if (fence)
      continue;
    const heading = checkHeading(editor.getLine(line));
    if (heading > 0) {
      headingLines.push(line);
      minHeading = setMin(minHeading, heading);
      maxHeading = setMax(maxHeading, heading);
    }
  }
  return { headingLines, minHeading, maxHeading };
};
var getPreviousHeading = (editor, from) => {
  let fence = null;
  let start = from > 0 ? from - 1 : 0;
  for (let line = start; line >= 0; line--) {
    fence = getFenceStatus(fence, checkFence(editor.getLine(line)));
    if (fence)
      continue;
    if (checkHeading(editor.getLine(line)) > 0) {
      return line;
    }
  }
  return void 0;
};

// src/features/applyHeading/module.ts
var regExp = { ol: new RegExp("\\d+\\."), ul: new RegExp("\\-|\\*") };
var applyHeading = (chunk, headingSize, settings) => {
  var _a;
  const replacer = Object.entries((_a = settings == null ? void 0 : settings.styleToRemove) != null ? _a : {}).flatMap(([k, v]) => {
    return v ? regExp[k].source : [];
  });
  const replaceStyleRegExp = new RegExp(`^(${replacer.join("|")}) `, "");
  const remove = chunk.replace(replaceStyleRegExp, "").replace(/^#+ /, "");
  if (headingSize <= 0)
    return remove;
  return new Array(headingSize).fill("#").reduce((prev, cur) => {
    return cur + prev;
  }, " ") + remove;
};

// src/features/applyHeading/operation.ts
var ApplyHeading = class {
  constructor(settings, headingSize) {
    __publicField(this, "settings");
    __publicField(this, "headingSize");
    __publicField(this, "editorCallback", (editor) => {
      const lines = createRange(editor.getCursor("from").line, editor.getCursor("to").line - editor.getCursor("from").line + 1);
      const isOneline = editor.getCursor("from").line === editor.getCursor("to").line;
      editor.transaction({
        changes: composeLineChanges(editor, lines, (chunk) => applyHeading(chunk, this.headingSize, this.settings))
      });
      if (isOneline) {
        editor.setCursor(editor.getCursor("anchor").line);
      }
      return true;
    });
    __publicField(this, "createCommand", () => {
      return {
        id: `apply-heading${this.headingSize}`,
        name: `Apply Heading ${this.headingSize}`,
        icon: `headingShifter_heading${this.headingSize}`,
        editorCallback: this.editorCallback
      };
    });
    __publicField(this, "check", () => {
      return this.settings.overrideTab;
    });
    this.settings = settings;
    this.headingSize = headingSize;
  }
};

// src/features/shiftHeading/module.ts
var shiftHeading = (chunk, dir, settings) => {
  const heading = checkHeading(chunk);
  return applyHeading(chunk, heading + dir, settings);
};
var increaseHeading = (chunk, settings) => {
  return shiftHeading(chunk, 1, settings);
};
var decreaseHeading = (chunk, settings) => {
  return shiftHeading(chunk, -1, settings);
};

// src/features/shiftHeading/operation.ts
var IncreaseHeading = class {
  constructor(settings) {
    __publicField(this, "settings");
    __publicField(this, "editorCallback", (editor) => {
      const { headingLines, maxHeading } = getHeadingLines(editor, editor.getCursor("from").line, editor.getCursor("to").line);
      if (maxHeading !== void 0 && maxHeading >= 6) {
        new import_obsidian4.Notice("Cannot Increase (contains more than Heading 6)");
        return true;
      }
      const editorChange = composeLineChanges(editor, headingLines, increaseHeading, this.settings);
      editor.transaction({
        changes: editorChange
      });
      return editorChange.length ? true : false;
    });
    __publicField(this, "createCommand", () => {
      return {
        id: "increase-heading",
        name: "Increase Headings",
        icon: "headingShifter_increaseIcon",
        editorCallback: this.editorCallback
      };
    });
    __publicField(this, "check", () => {
      return this.settings.overrideTab;
    });
    this.settings = settings;
  }
};
var DecreaseHeading = class {
  constructor(settings) {
    __publicField(this, "settings");
    __publicField(this, "editorCallback", (editor) => {
      const { headingLines, minHeading } = getHeadingLines(editor, editor.getCursor("from").line, editor.getCursor("to").line);
      if (minHeading !== void 0 && minHeading <= Number(this.settings.limitHeadingFrom)) {
        new import_obsidian4.Notice(`Cannot Decrease (contains less than Heading${Number(this.settings.limitHeadingFrom)})`);
        return true;
      }
      const editorChange = composeLineChanges(editor, headingLines, decreaseHeading, this.settings);
      editor.transaction({
        changes: editorChange
      });
      return editorChange.length ? true : false;
    });
    __publicField(this, "createCommand", () => {
      return {
        id: "decrease-heading",
        name: "Decrease Headings",
        icon: "headingShifter_decreaseIcon",
        editorCallback: this.editorCallback
      };
    });
    __publicField(this, "check", () => {
      return this.settings.overrideTab;
    });
    this.settings = settings;
  }
};

// src/features/insertHeading/operation.ts
var import_obsidian5 = require("obsidian");
var InsertHeadingAtCurrentLevel = class {
  constructor(settings) {
    __publicField(this, "settings");
    __publicField(this, "editorCallback", (editor) => {
      const cursorLine = editor.getCursor("from").line;
      const lastHeadingLine = getPreviousHeading(editor, cursorLine);
      const headingLevel = lastHeadingLine != void 0 ? checkHeading(editor.getLine(lastHeadingLine)) : 0;
      editor.transaction({
        changes: composeLineChanges(editor, [cursorLine], (chunk) => applyHeading(chunk, headingLevel))
      });
      editor.setCursor(editor.getCursor().line);
      return true;
    });
    __publicField(this, "createCommand", () => {
      return {
        id: `insert-heading-current`,
        name: `Insert Heading at current level`,
        icon: `headingShifter_heading`,
        editorCallback: this.editorCallback
      };
    });
    this.settings = settings;
  }
};
var InsertHeadingAtDeeperLevel = class {
  constructor(settings) {
    __publicField(this, "settings");
    __publicField(this, "editorCallback", (editor) => {
      const cursorLine = editor.getCursor("from").line;
      const lastHeadingLine = getPreviousHeading(editor, cursorLine);
      const headingLevel = lastHeadingLine ? checkHeading(editor.getLine(lastHeadingLine)) : 0;
      if (headingLevel + 1 > 6) {
        new import_obsidian5.Notice("Cannot Increase (contains more than Heading 6)");
        return true;
      }
      editor.transaction({
        changes: composeLineChanges(editor, [cursorLine], (chunk) => applyHeading(chunk, headingLevel + 1))
      });
      editor.setCursor(editor.getCursor().line);
      return true;
    });
    __publicField(this, "createCommand", () => {
      return {
        id: `insert-heading-deeper`,
        name: `Insert Heading at one level deeper`,
        icon: `headingShifter_heading`,
        editorCallback: this.editorCallback
      };
    });
    this.settings = settings;
  }
};
var InsertHeadingAtHigherLevel = class {
  constructor(settings) {
    __publicField(this, "settings");
    __publicField(this, "editorCallback", (editor) => {
      const cursorLine = editor.getCursor("from").line;
      const lastHeadingLine = getPreviousHeading(editor, cursorLine);
      const headingLevel = lastHeadingLine ? checkHeading(editor.getLine(lastHeadingLine)) : 0;
      editor.transaction({
        changes: composeLineChanges(editor, [cursorLine], (chunk) => applyHeading(chunk, headingLevel - 1, this.settings))
      });
      editor.setCursor(editor.getCursor().line);
      return true;
    });
    __publicField(this, "createCommand", () => {
      return {
        id: `insert-heading-higher`,
        name: `Insert Heading at one level higher`,
        icon: `headingShifter_heading`,
        editorCallback: this.editorCallback
      };
    });
    this.settings = settings;
  }
};

// src/services/registerService.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var RegisterService = class {
  constructor(plugin) {
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  exec() {
    this.addCommands();
  }
  addCommands() {
    const increaseHeading2 = new IncreaseHeading(this.plugin.settings);
    const decreaseHeading2 = new DecreaseHeading(this.plugin.settings);
    const insertHeadingAtCurrentLebel = new InsertHeadingAtCurrentLevel(this.plugin.settings);
    const insertHeadingAtDeeperLevel = new InsertHeadingAtDeeperLevel(this.plugin.settings);
    const insertHeadingAtHigherLevel = new InsertHeadingAtHigherLevel(this.plugin.settings);
    HEADINGS.forEach((heading) => {
      const applyHeading2 = new ApplyHeading(this.plugin.settings, heading);
      this.plugin.addCommand(applyHeading2.createCommand());
    });
    this.plugin.addCommand(increaseHeading2.createCommand());
    this.plugin.addCommand(decreaseHeading2.createCommand());
    this.plugin.addCommand(insertHeadingAtCurrentLebel.createCommand());
    this.plugin.addCommand(insertHeadingAtDeeperLevel.createCommand());
    this.plugin.addCommand(insertHeadingAtHigherLevel.createCommand());
    this.plugin.registerEditorExtension(import_state.Prec.highest(import_view.keymap.of([
      {
        key: "Tab",
        run: this.plugin.obsidianService.createKeymapRunCallback({
          check: increaseHeading2.check,
          run: increaseHeading2.editorCallback
        })
      }
    ])));
    this.plugin.registerEditorExtension(import_state.Prec.highest(import_view.keymap.of([
      {
        key: "s-Tab",
        run: this.plugin.obsidianService.createKeymapRunCallback({
          check: decreaseHeading2.check,
          run: decreaseHeading2.editorCallback
        })
      }
    ])));
  }
};

// src/main.ts
var HeadingShifter = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings");
    __publicField(this, "obsidianService");
    __publicField(this, "interfaceService");
    __publicField(this, "registerService");
  }
  onload() {
    return __async(this, null, function* () {
      this.obsidianService = new ObsidianService();
      this.interfaceService = new InterfaceService();
      this.registerService = new RegisterService(this);
      yield this.loadSettings();
      this.registerService.exec();
      this.interfaceService.exec();
      this.addSettingTab(new HeadingShifterSettingTab(this.app, this));
    });
  }
  onunload() {
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
